apiVersion: apps/v1
kind: Deployment
metadata:
  name: student10-deployment
  namespace: student10
spec:
  selector:
    matchLabels:
      app: student10
  template:
    metadata:
      labels:
        app: student10
    spec:
      containers:
      - name: student10
        image: registry.tanzu.dk/ops2devops/student10:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: studentx
spec:
  type: NodePort
  selector:
    app: student10
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30020 # Remember to change to student number.

